### ISSUE TITLE
Should SDL_GetDisplayUsableBounds return display size of size of the window?

### ISSUE THREAD

**Issue by daid** [emscripten-ports/SDL2#100]
After a bit of testing, I didn't find any portable way to get the size of the frame in which SDL2 is running in emscripten. Leaving me with the following code:
```
        SDL_GetDisplayUsableBounds(0, &display_mode);
#ifdef __EMSCRIPTEN__
        display_mode.w = EM_ASM_INT({ return window.innerWidth; });
        display_mode.h = EM_ASM_INT({ return window.innerHeight; });
#endif//__EMSCRIPTEN__
```
I think it would make sense if SDL_GetDisplayUsableBounds would return the size of the window, instead of the full screen display size. As generally, the SDL_GetDisplayUsableBounds is where you want to base your window size on if you are running windowed. But right now, this generates a too large canvas, especially if your application is running in an iframe (like on itch.io)

**Comment by Daft-Freak** [comment]
I think it makes sense, outside the window isn't "usable". Not going to be perfectly accurate (padding/margin/scrollbars/etc.), but definitely an improvement.

(Might be a while before I can implement/test anything though.)

**Comment by daid** [comment]
I could try building a patch. But I have no idea how to build&use a customized SDL2 source tree in emscripten, as everything is so automated.

**Comment by Daft-Freak** [comment]
You should be able to use `EMCC_LOCAL_PORTS`.
