### ISSUE TITLE
Is SDL_GL_SwapWindow(window) expected to work?

### ISSUE THREAD

**Issue by Toninoso** [emscripten-ports/SDL2#101]
Even if I clear my window to green the canvas background in HTML page remains black.

Code excerpt:

```
   // Request OpenGL ES 3.0
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
    // Want double-buffering
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);

    // Create the window
    window = SDL_CreateWindow("GLES3+SDL2 Tutorial", SDL_WINDOWPOS_UNDEFINED,
        SDL_WINDOWPOS_UNDEFINED, DISP_WIDTH, DISP_HEIGHT,
        SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN);

    context = SDL_GL_CreateContext(window);
     // Clear to green
    glClearColor(0.0f, 1.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    // Update the window
    SDL_GL_SwapWindow(window);

#ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(loop, 0, 1);
#else
    loop();
#endif
```
The loop code just does `SDL_PollEvent(&event)` for SDL_QUIT.
Compiled with:

`emcc BasicSDL.cpp --emrun -s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_SDL=2 -o WASM\BasicSDL.html
`

**Edit after original post:**
Eventually I got the green window background to display after changing the main loop update to
   ` emscripten_set_main_loop(loop, 60, 1);`

that is, frame rate of 60 instead of 0.

but then got a message:
 
`Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!`

I guess I need to read up on requestAnimationFrame. Please feel free to comment and/or recommend how to deal with this issue and then it should probably be closed or considered a documentation enhancement issue.

**Comment by Toninoso** [comment]
Quoting:
https://emscripten.org/docs/api_reference/emscripten.h.html#browser-execution-environment
(bold emphasis mine)

> . . . browser’s requestAnimationFrame will make sure you render at a proper smooth rate that lines up properly with the browser and monitor. **If you do not render at all in your application, then you should pick a specific frame rate that makes sense for your code**.

This would apply to my case since I was not rendering in my loop, just polling on quit event. 

There is still something else going on with SDL_GL_SwapWindow that I don't understand. Namely, I augmented my loop to change background to red, from initial green. This call appears to be ignored - window background remains green in the browser. 

However, running the same code in a desktop app behaves as expected - one sees a switch from initial green to red background.

```
#ifdef __EMSCRIPTEN__
void loop()
{
    // Wait for the user to quit
    while (!quit)
    {
       // clear to red
        glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        // Update the window
        SDL_GL_SwapWindow(window);

        SDL_Event event;
        if (SDL_PollEvent(&event) != 0)
        {
            if (event.type == SDL_QUIT)
            {
                // User wants to quit
                quit = true;
            }
        }
    }

    emscripten_cancel_main_loop();
}
#endif

```

**Comment by Daft-Freak** [comment]
You need to move the `while(!quit)` outside of `loop()`.

Something like:

```c
void loop()
{
    // clear to red
    glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    // Update the window
    SDL_GL_SwapWindow(window);

    SDL_Event event;
    if (SDL_PollEvent(&event) != 0)
    {
        if (event.type == SDL_QUIT)
        {
            // User wants to quit
            quit = true;
#ifdef __EMSCRIPTEN__
            emscripten_cancel_main_loop();
#endif
        }
    }
}

```

and

```c
#ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(loop, 0, 1);
#else
    while(!quit) loop();
#endif
```

(Though I don't think we send quit events...)

**Comment by Toninoso** [comment]
Ouch! So dumb from me to put a tight polling loop inside emscripten loop invocation.
Of course, it works now.
I'll use some keystroke event to quit the loop, instead of polling for SDL_QUIT.
Many thanks!
