### ISSUE TITLE
SDL UWP

### ISSUE THREAD

**Issue by brunotrevisan** [emscripten-ports/SDL2#103]
is there a document to use SDL2 UWP?

ReadOnlySpan <byte> data, int width, int height, int pitch

I receive the following information from a dll and I need to render it the image is in this byte array. How can I achieve this with SDL? another question besides C ++ is there a possibility to use it in C #?

**Comment by brunotrevisan** [comment]
I also didn't find how to link to a SwapChainPanel, is there any documentation that I can read? I'm really lost on the subject


if possible give me a small example of drawImage bytes with a SwapChainPanel I thank

**Comment by Daft-Freak** [comment]
This repo is only for the Emscripten port of SDL2, you could try asking on [the forums](https://discourse.libsdl.org/).
