### ISSUE TITLE
Please tag version_19

### ISSUE THREAD

**Issue by Beuc** [emscripten-ports/SDL2#107]
Hi,

Would you mind creating a new tag, and import it in Emscripten's ports?

version_18 is from June 2019 and lacks important fixes.
Emscripten also makes it pretty inconvenient to work on a patched SDL2 port.

**Comment by kripken** [comment]
Sure, I tagged and opened https://github.com/emscripten-core/emscripten/pull/10690 now.

I agree it would be a good idea to make it easier to use a patched port. I don't have good ideas for that myself, but hopefully someone else does + time.

**Comment by Beuc** [comment]
Thanks @kripken !
