### ISSUE TITLE
TypeError: GLctx is undefined

### ISSUE THREAD

**Issue by jplatte** [emscripten-ports/SDL2#11]
I get this error whenever calling `gl*` from my C++ code that's compiled with `-s USE_SDL=2` and `-s FULL_ES2=1`. It worked before porting it from SDL 1.3 (I guess) to SDL2.

**Comment by kripken** [comment]
Do you have a testcase? I build a random test with those flags (`sdl2_gl_read.c`) and it ran ok.

**Comment by jplatte** [comment]
I'll try to produce one.

**Comment by jplatte** [comment]
Oookay, so trying to reproduce this took very long, but in the end I figured out what was wrong: the problem was somehow caused by passing uninitialized variables (or maybe default-initialized, they were set to 0 anyway) to `SDL_GL_SetAttribute([...])` for `SDL_GL_CONTEXT_MAJOR_VERSION` and `SDL_GL_CONTEXT_MINOR_VERSION`.

I really can't comprehend how this could result in such an error, but I've fixed it now.
