### ISSUE TITLE
Update to SDL 2.0.12

### ISSUE THREAD

**Issue by albertvaka** [emscripten-ports/SDL2#122]
Could the port of SDL2 be updated to the latest version?

2.0.10 introduced [1] a few useful SDL_Render*F() functions that take floats, which aren't available in the current version of the precompiled port. 

Thanks!

[1] https://github.com/spurious/SDL-mirror/commit/a5ff4975953e48ca0c4be248717c70d69504eb2e#diff-e3d80b161b06ffe2881e04ff7df02f66

**Comment by Daft-Freak** [comment]
I have a merge of 2.0.10 here from a while back: https://github.com/emscripten-ports/SDL2/tree/merge-2.0.10

I just need to test it...

(You can edit `tools/ports/sdl2.py` with
```py
TAG = 'merge-2.0.10'
HASH = '65eaa45e7a6d857c3bc486b89f77c894d50a5ae55c50c73d5b86ef3706bee04620aca3b7dbec7b41d545846f78987b892c2c59961fea02a326677df14ec6b04f'
```
to try using it.)

**Comment by albertvaka** [comment]
I'll give it a test and get back to you sometime soon.

**Comment by tortoisedoc** [comment]
Hey, we would have the same need to have the SDL bumped to 2.0.12 for support for newer PS5 / XBOX Series X gamepads. ANy chance to have it?
