### ISSUE TITLE
How to force latest port version?

### ISSUE THREAD

**Issue by kevzettler** [emscripten-ports/SDL2#124]
I would like to try https://github.com/emscripten-ports/SDL2/commit/865eaddffed50dbd13e6564c3f73902472cf74e8

in a project of mine that currently has broken audio in chrome but is fine in firefox and edge. Can I manually pin this commit? What is the release process like?

**Comment by Daft-Freak** [comment]
You can modify the `TAG` in `tools/ports/sdl2.py` to the full commit id for a quick test.

**Comment by kripken** [comment]
You can also change the URL there to point to a fork of the repo, etc. as needed.

**Comment by kevzettler** [comment]
Thanks ya'll I got it imported and also it fixed the audio issue in chrome!
