### ISSUE TITLE
Multitouch problem

### ISSUE THREAD

**Issue by renehorstmann** [emscripten-ports/SDL2#139]
I am writing some Apps in SDL, that also use multi touch.

If I execute SDL_GetNumTouchDevices() on my Android phone, I get 0 devices. 

However, the Emscripten HTML5 Api for (multi) touch works fine.

Edit: I checked both Chrome and Samsung Internet on my Galaxy Note 8 device...

**Comment by Daft-Freak** [comment]
Haven't tested this, but I suspect that it will only return 1 after receiving the first touch event.

**Comment by renehorstmann** [comment]
Thanks, thats how it works.
