### ISSUE TITLE
Symbol `SDL_uclibc_exp` is not exported

### ISSUE THREAD

**Issue by ericoporto** [emscripten-ports/SDL2#143]
Explained here: https://github.com/sezero/SDL_sound/issues/6

This is required for other libraries that require `SDL_exp` (SDL implementation of C `exp()`).

**Comment by sezero** [comment]
The issue does _not_ seem to be about exporting SDL_uclibc_exp, but
about building `src/libm/e_exp.c` and including it in the build, because
`SDL_exp` calls it.

**Comment by ericoporto** [comment]
@sezero you are right, I noticed it's not here: https://github.com/emscripten-core/emscripten/blob/4e35687f2dca1171eca0735820d4f7f5ac65f363/tools/ports/sdl2.py#L42

I will try to add it here and see if it fix.
