### ISSUE TITLE
"Fullscreen" button fails in Firefox when not using WebGL and not preloading files

### ISSUE THREAD

**Issue by dreamlayers** [emscripten-ports/SDL2#15]
This is the first point listed at #8 and I also [mentioned it before in the Emscripten SDL2 port issue](https://github.com/kripken/emscripten/issues/2404#issuecomment-70956013).

To reproduce this problem, run an SDL 2 program which uses `SDL_Surface` and not `SDL_Renderer` for output. You can use [tests/sdl2_canvas_write.cpp from Emscripten](https://github.com/kripken/emscripten/blob/incoming/tests/sdl2_canvas_write.cpp). Don't run it normally via `runner.py`, because it is not interactive and would get closed automatically. Instead, build it stand-alone using `emcc '-DREPORT_RESULT()' -s USE_SDL=2 sdl2_canvas_write.cpp -o sdl2_canvas_write.html`. 

Open the test in Firefox, and then click the `Fullscreen` button in the top right of the page. If prompted for permission, click Allow. Note how the patterned square only takes up a small area in the top. It should be filling the screen from top to bottom. Now press `Esc` to exit full screen mode. Note grey `Exception thrown, see JavaScript console`. In web console, you will see `TypeError: canvas.requestPointerLock is not a function` from within the `fullScreenChange()` function. This happens in Firefox 36.0.1 and Firefox nightly 39.0a1 (2015-03-12). There is no problem in Chrome 41. The test will work in Firefox if you preload a file, for example adding `--preload-file sdl2_canvas_write.cpp` to the command line when building.

This happens because `Browser.init()` is not called. That function [sets `canvas.requestPointerLock()` to the appropriate browser-specific function](https://github.com/kripken/emscripten/blob/incoming/src/library_browser.js#L239).

SDL1 creates the canvas context via [`Browser.createContext()`](https://github.com/kripken/emscripten/blob/incoming/src/library_browser.js#L268), which in turn calls `Browser.init()`. Here's how SDL 2 calls the function when using WebGL:
```
Browser.init (test.js:6263)
Browser.createContext (test.js:6480)
_glutCreateWindow (test.js:9174)
_eglCreateContext (test.js:9204)
_eglCreateContext__wrapper (test.js:156590)
_SDL_EGL_CreateContext (test.js:34147)
_Emscripten_GLES_CreateContext (test.js:45323)
_SDL_GL_CreateContext (test.js:44176)
_GLES2_CreateRenderer (test.js:110057)
_SDL_CreateRenderer (test.js:18943)
```
When SDL 2 uses Surface output, it [calls `getContext('2d')` directly](https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenframebuffer.c#L79). Should it be using `Browser.createContext()`?

**Comment by kripken** [comment]
Yes, I think it should call `Browser.createContext` (probably with `(canvas, false, true)`).

**Comment by kripken** [comment]
I'm not at a machine where I can test it right now, but I could do it next week, unless you want to check earlier.

**Comment by kripken** [comment]
Done in ac447b92717164c0a520c518f1d309e909c06574
