### ISSUE TITLE
Create a version_25 tag + release so emscripten-core can be updated to use it

### ISSUE THREAD

**Issue by thomasballinger** [emscripten-ports/SDL2#156]
It looks to me like Emscripten needs a release in order to update the SDL2 version. If this is right, could a new release please be created so I can make a PR adding the new version to Emscripten?

relevant bit in Emscripten's sdl2.py file:
https://github.com/emscripten-core/emscripten/blob/0b0790980211179f85ad9fbf9b48b6d6aa6370ff/tools/ports/sdl2.py#L8-L9

**Comment by kripken** [comment]
I think we are close to just pointing emscripten at upstream SDL2,

https://github.com/emscripten-core/emscripten/pull/15452

Hopefully that lands soon!
