### ISSUE TITLE
Emscripten : error: undefined symbol: SDL_strtokr

### ISSUE THREAD

**Issue by ericoporto** [emscripten-ports/SDL2#159]
Detailed here: https://github.com/libsdl-org/SDL/issues/5216

Also it would be useful to know what the use SDL=2 flag is getting, this repo or the SDL repo. I am building with latest emsdk and it was weird seeing my CI start failing without any code changes. :/

I saw the readme but I still don't know, are we really getting SDL2 upstream? Is from release or whatever is in main? If I use a specific version of EMSDK, which version of SDL2 I get?

I would prefer to be able to specify an EMSDK version and this then specify the version of everything else, as a known package that is known to build alright.

**Comment by Daft-Freak** [comment]
Since https://github.com/emscripten-core/emscripten/pull/15452 it's fetched from upstream (currently the `release-2.0.18` tag).

I'm guessing the "no undefined symbols" test didn't catch this one because none of the SDL sources we build use it...

**Comment by ericoporto** [comment]
I think I am the [spacebar heating person](https://xkcd.com/1172/) 😕
