### ISSUE TITLE
#include <SDL2/SDL.h> doesn't work

### ISSUE THREAD

**Issue by lolzballs** [emscripten-ports/SDL2#16]
On my linux setup, the default include path for SDL2 is at SDL2/SDL.h, but in this port it is just SDL.h. When I went digging around the the ports.py file, I found
```
# copy includes to a location so they can be used as 'SDL2/'
include_path = os.path.join(shared.Cache.get_path('ports-builds'), 'sdl2', 'include')
shared.try_delete(os.path.join(include_path, 'SDL2'))
shutil.copytree(include_path, os.path.join(include_path, 'SDL2'))
```

I don't really know python, but based on the comment, I think `#include <SDL2/SDL.h>` is supposed to work.

**Comment by mgerhardy** [comment]
It's fine to only include SDL2.h without the directory. You need to call pkg-config or set up your include search paths properly in your build scripts.

**Comment by lolzballs** [comment]
The problem, is that the normal include path is at SDL2/SDL.h.

As well, based on the [tests](https://github.com/kripken/emscripten/blob/master/tests/sdl2_key.c]), it should work like that in emscripten too.

Maybe I need to add a include path to my cmake files?
