### ISSUE TITLE
Automatic fallback to Canvas?

### ISSUE THREAD

**Issue by wiseoldman95** [emscripten-ports/SDL2#17]
Currently, when one uses SDL_Renderer, WebGL is a must. If the browser does not have WebGL, the program will not work.
On the other hand, when SDL_Surface is used without SDL_Renderer, WebGL is not needed and an HTML5 canvas is used.

Perhaps there should be an automatic fallback, which emulates SDL_Renderer with an SDL_Surface internally when WebGL is not detected.

**Comment by wiseoldman95** [comment]
Creating the renderer with the SDL_RENDERER_SOFTWARE alone makes it all work without WebGL
`sRenderer = SDL_CreateRenderer( sWindow, -1, SDL_RENDERER_SOFTWARE);`
Sorry for bothering you.

**Comment by zwhitchcox** [comment]
Thanks for the tip!
