### ISSUE TITLE
Scan codes not detected

### ISSUE THREAD

**Issue by Zelif** [emscripten-ports/SDL2#18]
Not sure if there are limitations or not but would there be a reason for some of the scan codes not to work?
These are the ones I was trying to use:
SDL_SCANCODE_VOLUMEUP
SDL_SCANCODE_VOLUMEDOWN
SDL_SCANCODE_AUDIONEXT
SDL_SCANCODE_AUDIOPREV
SDL_SCANCODE_AUDIOPLAY
SDL_SCANCODE_AUDIOMUTE
Not sure if any other of the scan codes don't work. 

It works as expected on the desktop, but as soon as I compile it, the scancodes only get basic keys like space all the letters. 
Is this a limitation of running in the browser or a bug? 

Im checking the keyboard with
```
Uint8 * keyArray = SDL_GetKeyboardState(NULL)
keyArray [SCAN_CODE]
```

Browser: Chrome 42

**Comment by Daft-Freak** [comment]
Keys are mapped using this table:
https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenevents.c#L44

If you know the value reported for .which it should be possible to add those.

**Comment by Zelif** [comment]
Not sure if these are the values you are after:
These is what Javascript reports when I press those keys.
 ```
MediaPreviousTrack  177
MediaPlayPause      179
MediaNextTrack      176
VolumeMute          173
VolumeDown          174
VolumeUp            175
```
Strange thing is 
https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenevents.c#L218 has 
``` /* 173 */   SDL_SCANCODE_MINUS, /*FX*/```

Not sure why this has been remapped to minus but if I use 
``` SDL_SCANCODE_MINUS ```
instead of 
``` SDL_SCANCODE_AUDIOMUTE ```
it registers when I press the audio mute key, and breaks the desktop version.

**Comment by Daft-Freak** [comment]
This should fix most of those. 
95b9b62590d4dcb1f97798310165dcce505cc8a8

**Comment by Zelif** [comment]
Cheers for that. :D 

Not sure how its going to turn out but I think I'm going to try tackle using the DOM lvl 3 event keys. If the browsers implement that spec correctly -glares at IE- that should be a better method of linking all the keys.
