### ISSUE TITLE
Mouse input is broken in all browsers

### ISSUE THREAD

**Issue by TelpeNight** [emscripten-ports/SDL2#2]
https://github.com/emscripten-ports/SDL2/commit/8d47621114eb254c33a35a44bfac39b3d7d4dca2

This commit breaks input handling in all browsers.
See emscripten's `fillMouseEventData`. Pay attention to this line.

    var rect = (target === window) ? { left: 0, top: 0 } : target.getBoundingClientRect();

Now it's executed with `target == document`, with `getBoundingClientRect` undefined.

**Comment by Daft-Freak** [comment]
That was https://github.com/kripken/emscripten/issues/3060, which is fixed from emscripten 1.28.0

**Comment by TelpeNight** [comment]
This issue is closed. Please, see kripken/emscripten#3144 for further discussion.
