### ISSUE TITLE
crash on very long SDL_Log string parameter

### ISSUE THREAD

**Issue by salos1982** [emscripten-ports/SDL2#24]
I have crash when I try to log response from my server. I try to print
SDL_Log("decoded request: %s", textReponse);
textResponse has length about 6500 bytes.
the issue is in file SDL_log.c in function SDL_LogMessageV.
It does not check return value of SDL_vsnprintf
that can be negative if not enough buffer length. In this case message variable can have no nul terminating character and following SDL_strlen can crash

**Comment by Daft-Freak** [comment]
This looks like an upstream issue. We don't modify SDL_log.
