### ISSUE TITLE
configuration error in ubuntu

### ISSUE THREAD

**Issue by georgooty** [emscripten-ports/SDL2#28]
Hi,

I downloaded the source code then I trying to build the source code compatible with the nacl. So I downloaded the nacl sdk and installed pepper version 47. 

Then I executed the below command, but I got the below error, 

> 
> gk@ubuntu:~/Desktop/SDL2-master$ sudo ./build-scripts/naclbuild.sh /home/gk/Desktop/nacl_sdk/pepper_47/
> [sudo] password for gk: 
> Using SDK at /home/gk/Desktop/nacl_sdk/pepper_47/
> checking build system type... i686-pc-linux-gnu
> checking host system type... le32-unknown-pnacl
> checking how to print strings... printf
> checking for pnacl-gcc... /home/gk/Desktop/nacl_sdk/pepper_47//toolchain/linux_pnacl/bin/pnacl-clang
> checking whether the C compiler works... no
> configure: error: in `/home/gk/Desktop/SDL2-master/build/nacl':
> configure: error: C compiler cannot create executables
> See `config.log' for more details
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target `install'.  Stop.
> Build failed! /home/gk/Desktop/SDL2-master/build/nacl/build/.libs/libSDL2.a

Can you check it,

Regards,
George

**Comment by Daft-Freak** [comment]
This repo is only for the Emscripten port of SDL2. You could try [the upstream bug tracker](https://bugzilla.libsdl.org/).
