### ISSUE TITLE
tfinger coodrinates are inconsistent with desktop version

### ISSUE THREAD

**Issue by maatee90** [emscripten-ports/SDL2#31]
SDL2's SDL_FINGER* events report normalized (0...1,0...1) client coordinates (in tfinger.x and tfinger.y) compiled fot WIN32 target. The same variables are non-normalized(0...width-1,0...height-1) client corrdinates when compiled with emscripten (sdk-1.35.0-64 bit, SDL2-version_9).

**Comment by maatee90** [comment]
I see [67d7b26b5d7aa454e47bc186418c6d861ed37d54](https://github.com/emscripten-ports/SDL2/commit/67d7b26b5d7aa454e47bc186418c6d861ed37d54) fixes the problem.
When will emscripten use version 11?

**Comment by Daft-Freak** [comment]
I think that change is in version 10 which emscripten  has used since 1.35.21 (11 is available on incoming). If you don't want to upgrade your emscripten for some reason you can change `TAG` at the top of `tools/ports/sdl.py`

**Comment by maatee90** [comment]
Thanks!
