### ISSUE TITLE
Issue with SDL_OpenAudio called more than once.

### ISSUE THREAD

**Issue by Kaosumaru** [emscripten-ports/SDL2#33]
I've noticed, that if you call SDL_OpenAudio more than once (ie open, close, open), produced sound is very choppy - it looks like half of samples are being eaten up by the old callback, though I might be wrong.

I've attached modified sdl2._audio_beep.cpp [sdl2_audio_beep.zip](https://github.com/emscripten-ports/SDL2/files/536538/sdl2_audio_beep.zip), which plays beep twice with 48000/F32 (only format that seems to work in most browsers) - second playback is extremely wrong.

**Comment by Daft-Freak** [comment]
Looks like we're missing cleanup in `Emscripten_CloseDevice`. (https://github.com/emscripten-ports/SDL2/blob/master/src/audio/emscripten/SDL_emscriptenaudio.c#L139).

**Comment by Kaosumaru** [comment]
Yup, seems to work now. I'm closing it.
