### ISSUE TITLE
Resource file fails to build with NMake

### ISSUE THREAD

**Issue by 73UJ34** [emscripten-ports/SDL2#35]
When building SDL2 with -G "NMake Makefiles" the 'src/main/windows/version.rc' file fails with:

fatal error RC1203: invalid hexadecimal default language ID specified

**Comment by AlexiaChen** [comment]
Have you solve this problem?   I have encountered this issue, with VS2013 & CMake,  too

**Comment by Daft-Freak** [comment]
This doesn't look like an Emscripten issue (.rc files are windows specific). If this is still an issue, you should check the upstream bug tracker.
