### ISSUE TITLE
Keyboard input does not work for SDL2

### ISSUE THREAD

**Issue by thomasarnbjerg** [emscripten-ports/SDL2#36]
Messages SDL_TextInput, SDL_KeyDown and SDL_KeyUp don't work and keyboard input cannot be used.

The events are generated correctly but:

For the event SDL_TextInput the attributes in struct SDL_TextInputEvent::text are not properly filled and the text entered cannot be retrieved (e.g. attribute TextInputEvent::text::text).

The same goes for the attributes in struct SDL_KeyboardEvent for the events SDL_KeyUp and SDL_KeyDown.

The test in sdl2_key.c for emscripten 1.35 should reveal this (btw it seems to be broken since it refers to non-existing headers and API calls). 

The problem is seen on emscripten 1.35.0 (prebuilt Windows binaries) on windows 7 (64 bit) and Firefox 50.1.0

**Comment by Daft-Freak** [comment]
Make sure you're using `-s USE_SDL=2` when compiling and linking, otherwise the wrong headers end up getting included and the event data ends up broken.

**Comment by thomasarnbjerg** [comment]
This is my compile line:

%EMSCRIPTEN_HOME%/em++.bat --bind -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_FREETYPE=1 -s USE_SDL_IMAGE=2 -s ALLOW_MEMORY_GROWTH=1 -s SDL2_IMAGE_FORMATS="[""png""]" --embed-file ..\resources@/resources --std=c++11 -g0 -O3 -I"../libs" -I"../src" -o ../Release %PATHS%

- where %PATHS% contains the files to compile.

**Comment by Daft-Freak** [comment]
Here's a modified sdl2_key that works standalone.
```
#include <stdio.h>
#include <SDL2/SDL.h>
#include <emscripten.h>

int result = 1;

int EventHandler(void *userdata, SDL_Event *event) {
  int mod;
  
  switch(event->type) {
    case SDL_KEYUP:
      break;
    case SDL_KEYDOWN:
      switch (event->key.keysym.sym) {
        case SDLK_RIGHT: printf("right\n"); result *= 7; break;
        case SDLK_LEFT: printf("left\n"); result *= 11; break;
        case SDLK_DOWN: printf("down\n"); result *= 13; break;
        case SDLK_UP: printf("up\n"); result *= 17; break;
        case SDLK_a: printf("a\n"); result *= 19; break;
        default: {
          if (event->key.keysym.scancode == SDL_SCANCODE_B) {
            printf("b scancode\n"); result *= 23; break;
          }
          printf("unknown key: sym %d scancode %d\n", event->key.keysym.sym, event->key.keysym.scancode);
        }
      }
      break;
    case SDL_TEXTINPUT:
      if (event->text.text[0] == 'A') {
        printf("a\n");result *= 5;
      }
      break;
    default: /* Report an unhandled event */
      printf("I don't know what this event is (type=%d)!\n", event->type);
  }
  return 0;
}

void one() {
  SDL_Event event;
  while (SDL_PollEvent(&event)) {
    EventHandler(0, &event);
  }
}

int main(int argc, char **argv) {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Window *window;
  window = SDL_CreateWindow("sdl2_key",
                            SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                            640, 480, 0);


  SDL_StartTextInput();

  emscripten_set_main_loop(one, 0, 1);

  return 0;
}

```
`emcc sdl2_key.c -s USE_SDL=2 -o sdl2_key.html`

**Comment by thomasarnbjerg** [comment]
I can see this works. I suspect the problem is exactly that I include the wrong header as you described. Thanks for the help.
