### ISSUE TITLE
Browser Unzoom at startup results in truncated canvas

### ISSUE THREAD

**Issue by pdox** [emscripten-ports/SDL2#37]
This happens on both Chrome and Firefox.

1) Set browser zoom to 75%.

2) Load any emscripten SDL2 application which paints to its entire window.
    (For example, em-dosbox as posted at: http://pdox.net/dosbox/dosbox.html )

3) The canvas output will truncated.

I've traced the problem to Emscripten_SetWindowSize() which scales the canvas size by emscripten_get_device_pixel_ratio(). I'm not sure of the intended behavior behind this action.

**Comment by Daft-Freak** [comment]
The scaling is for HiDPI. We seem to be missing a check for `SDL_WINDOW_ALLOW_HIGHDPI` actuallt being set though.

**Comment by Daft-Freak** [comment]
Should be fixed by f9e76e476d9e9ff97f6efa2b3518b23aff005a04
