### ISSUE TITLE
Canvas resizing problems on orientation change

### ISSUE THREAD

**Issue by jefvel** [emscripten-ports/SDL2#40]
There is an issue when creating a window with the SDL_RESIZABLE flag on. 
When changing orientation on phones (I've tried it on Android and Ios), the canvas will be much larger than the screen resolution, causing slowdowns, and the window only to be rendered onto a fourth of the screen.

**Comment by jefvel** [comment]
screenshots:
First:
http://i.imgur.com/Nk6l7uv.png

After orientation change:
http://i.imgur.com/F04XCn3.png

Going back to horizontal:
http://i.imgur.com/XmrLmC4.png

Try it here in a browser: http://jefvel.net/~jefvel/sdltest/

**Comment by Daft-Freak** [comment]
If you're not using the `SDL_WINDOW_ALLOW_HIGHDPI` flag, this may be the issue fixed in f9e76e476d9e9ff97f6efa2b3518b23aff005a04. You can try changing `TAG` in `tools/ports/sdl.py` to `version_13` to see if that helps.

**Comment by jefvel** [comment]
Ah, thank you very much! Your fix solved the error! This issue is fixed.
