### ISSUE TITLE
preventDeafult for mouseup breaks HTML5 range input control

### ISSUE THREAD

**Issue by kichikuou** [emscripten-ports/SDL2#41]
Initially filed as kripken/emscripten#3926.

[SDL2 consumes mouseup events on Document](https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenevents.c#L611), but that breaks HTML5 range input control.

- Chrome / Safari: the range control captures the mouse and never releases
- Firefox: when the cursor leaves, the slider returns to its original position.

Example page to demonstrate the issue: https://jsfiddle.net/fh5pLfn6/1/

This happens even if the mouse operation is done entirely outside the canvas area. Can we stop consuming mouseup?

**Comment by Daft-Freak** [comment]
I don't know if consuming the event is needed to avoid some unwanted browser behaviour. We should probably just return false if the mouse is outside of the canvas though.

**Comment by infval** [comment]
Chrome doesn't have this issue anymore.
Firefox fix (it's working for me):
```javascript
var slider = document.getElementById("slider");
slider.addEventListener("mousemove", function (event) {
  Module.ccall('SetVolume', 'void', ['number'], [event.target.value]);
}, false);
// Firefox fix, https://github.com/emscripten-ports/SDL2/issues/41
slider.addEventListener("mouseup", function (event) {
  event.target.blur();
}, false);
```

**Comment by scashews** [comment]
The firefox fix works, but Safari is still broken. I would ignore this except I can't even find a workaround... Using sliders just doesn't work with emscripten SDL at all... once you click, it's stays grabbed :(

**Comment by infval** [comment]
Bug is still here if range input control is inside of the canvas. :disappointed:
![Clipboard 1](https://user-images.githubusercontent.com/38145742/56478543-e299c880-64b8-11e9-9737-c213cac4c17c.png)
