### ISSUE TITLE
SDL_SYSTEM_CURSOR_SIZEALL not implemented

### ISSUE THREAD

**Issue by echeese** [emscripten-ports/SDL2#54]
Calling `SDL_CreateSystemCursor` with `SDL_SYSTEM_CURSOR_SIZEALL` does not affect the cursor. The rest of the cursors seem to work fine. The CSS `cursor` value should be set to `move`

**Comment by Daft-Freak** [comment]
Looks like I missed that one when I write the initial code: https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenmouse.c#L167
