### ISSUE TITLE
No sound in chrome - due to Autoplay policy changes

### ISSUE THREAD

**Issue by Kaosumaru** [emscripten-ports/SDL2#57]
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes are live, and this causes audioContext to be muted if it isn't created after user interaction. 
I've added quick work-around to my code:

document.addEventListener("click", function(){
    try {
        if (!SDL2 || !SDL2.audioContext || !SDL2.audioContext.resume) return;
            SDL2.audioContext.resume();
        } catch (err) {}
});

Maybe something like this (+keyboard events) should be added to SDL port?

**Comment by kripken** [comment]
After discussion there, there is no obvious generic solution, so yes, we probably should add code like that. @Kaosumaru, do you want to open a pull request perhaps?

**Comment by Kaosumaru** [comment]
Sorry for late reply - I'll try to prepare something in spare time :)

**Comment by Beuc** [comment]
Feel free to use my code btw.
https://github.com/emscripten-core/emscripten/issues/6511#issuecomment-483039500
