### ISSUE TITLE
Fails when trying to create OpenGL ES 3 (WebGL 2) context

### ISSUE THREAD

**Issue by Wolfos** [emscripten-ports/SDL2#59]
When using the attributes:
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);

It will return the error:
    Could not create EGL context

But it works when using 2.0

**Comment by Daft-Freak** [comment]
Are you using `-s USE_WEBGL2=1`?

**Comment by Wolfos** [comment]
Yes, here are all the flags I set:

LINK_FLAGS "-Os -s ALLOW_MEMORY_GROWTH=1 -s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s WASM=1 --preload-file ${CMAKE_SOURCE_DIR}/Assets@Assets --bind"

**Comment by Wolfos** [comment]
In case more info is needed, the repository is here:
https://github.com/Wolfos/WolfEngine/tree/emscripten

**Comment by Daft-Freak** [comment]
Looks like an issue with Emscripten's EGL support: https://github.com/kripken/emscripten/blob/incoming/src/library_egl.js#L284

**Comment by isc30** [comment]
as a workaround, if you omit the version hints for emscripten and compile using `-s USE_WEBGL2=1` it works like a charm.

```
void Window::initOpenGL()
{
    #ifndef __EMSCRIPTEN__
        // WebGL 2.0 == OpenGL ES 3.0
        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
    #endif

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 32);
}
```

**Comment by Daft-Freak** [comment]
Should work as of https://github.com/kripken/emscripten/pull/7858

**Comment by ongamex** [comment]
Hey guys, what is the status of this? with the latest Emscripten version 1.39.0 with the workaround above
I get
GLVersion = OpenGL ES 2.0 (WebGL 1.0)
vendor = Mozilla
renderer = Mozilla

and I end up not getting WebGL 2 (happens on Chrome as well).

The interesting part(at least to me as I do not know how Emscripten works) is that I use Queries and it links, and when I create query it crashes.

**Comment by Daft-Freak** [comment]
Since the change mentioned above, you don't need the workaround. In fact, you need to specify `SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3)` to get WebGL 2.

**Comment by ongamex** [comment]
Hey thanks for the replay!

The problem was caused because I did not called SDL_Init(SDL_INIT_VIDEO), as in some other thread I read that It was causing crashes (and iny my cases SDL_Init(SDL_INIT_EVERYTHING did, so just assumed that it is going to crash always).

After I've adding SDL_Init(SDL_INIT_VIDEO), everything worked and I managed to create a WebGL 2 context.

Here is a minimal example for any wanderers who might fight the same problem:

```
#include <SDL2/SDL.h>
#include <emscripten.h>
#include <GLES3/gl3.h>

extern "C" int main(int argc, char** argv) {
	printf("hello, world!\n");
	
	SDL_Init(SDL_INIT_VIDEO);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);

	SDL_Window* const wnd = SDL_CreateWindow("Tut0Wnd", 
		SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 
		400, 400,
		SDL_WINDOW_OPENGL);
		
	SDL_GL_CreateContext(wnd);

	const GLubyte* glVersion = glGetString(GL_VERSION);
	printf("GLVersion = %s\n", glVersion);
	
	const GLubyte* vendor = glGetString(GL_VENDOR);
	const GLubyte* renderer = glGetString(GL_RENDERER);
	printf("vendor = %s\nrenderer = %s\n", vendor, renderer);

	GLuint q;
	glGenQueries(1, &q);
	printf("If you see this there was no crash!\n");
	
	return 0;
}
```

Compiled with:
```
emcc tut0.cpp -o tut0.html -s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_SDL=2 -s WASM=0 -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s ALLOW_MEMORY_GROWTH=1

with emcc build:
emcc (Emscripten gcc/clang-like replacement) 1.39.0 (commit e047fe4c1ecfae6ba471ca43f2f630b79516706b)
```

**Comment by Daft-Freak** [comment]
Hmm, not getting a crash with the example and `-O2` here.

(`SDL_INIT_EVERYTHING` fails because we don't implement the haptic or sensor subsystems.)

**Comment by Wolfos** [comment]
Closing this because the issue has been fixed.
