### ISSUE TITLE
Pausing/closing audio repeats the buffer in Chromium indefinitely

### ISSUE THREAD

**Issue by dos1** [emscripten-ports/SDL2#69]
When using SDL_PauseAudioDevice or SDL_CloseAudioDevice, the sound doesn't stop in Chromium - instead, the last buffer contents seems to be repeated indefinitely (remember the bluescreens in Windows 9x? ;)).

Works as expected in Firefox.

Tested with Emscripten 1.38.21.

**Comment by dos1** [comment]
Just noticed that bc41280cf2c8618a0734e5ff04e3196de894c295 isn't included in a release yet. Not sure if it's really it, as pausing seems to be also affected, but it might be. Is there some easy way to use a HEAD version of the port?

**Comment by dos1** [comment]
Looking at the code, I don't see any support for actually pausing the AudioContext (https://webaudio.github.io/web-audio-api/#dom-audiocontext-suspend) - might be a good thing to actually add to reduce CPU and power usage when audio device is paused.

**Comment by kripken** [comment]
You can edit `toolsports/sdl.py` and change the tag to any branch, so e.g. `master` instead of `version_15`, for testing.

**Comment by dos1** [comment]
Thanks!

...but nope, doesn't help.

**Comment by infval** [comment]
I have similar issue when switch tabs or minimize Chrome. My fix:
```
window.addEventListener("blur", function() {
  pauseAudio(1);
}, false);
window.addEventListener("focus", function() {
  pauseAudio(0);
}, false);

// FIX (Chrome, ...?), project.js -> ASM_CONSTS
// https://github.com/emscripten-ports/SDL2/blob/master/src/audio/emscripten/SDL_emscriptenaudio.c
function pauseAudio(on) {
  if (typeof Module === 'undefined'
    || typeof Module.SDL2 == 'undefined'
    || typeof Module.SDL2.audioContext == 'undefined')
    return;
  if (on) {
    Module.SDL2.audio.scriptProcessorNode.disconnect();
  }
  else {
    Module.SDL2.audio.scriptProcessorNode['connect'](Module.SDL2.audioContext['destination']);
  }
}
```

**Comment by avivbeeri** [comment]
This workaround does the job... but it would be nice if it wasn't necessary. Any chance of this being fixed some time soon?

**Comment by Daft-Freak** [comment]
Might just be a case of filling the buffer with 0s in the `if(!enabled || paused)` branch... but I need to find something using audio to test with.

**Comment by atomheartother** [comment]
Is there any kind of workaround to the problem mentioned in the OP? This is still happening on Chrome. Worse, the device keeps looping the buffer but the audioCallback function is not called, so I can't even fill the buffer with 0s when I want to pause the audio device.
