### ISSUE TITLE
How to test changes to this port?

### ISSUE THREAD

**Issue by BenjaminTrapani** [emscripten-ports/SDL2#78]
What are the steps required to build and test changes to this port? Is there a way to configure the emsdk scripts to build a fork of this repo?

**Comment by kripken** [comment]
There is an `EMCC_LOCAL_PORTS` env var, see the comments and examples here:

https://github.com/emscripten-core/emscripten/blob/incoming/tools/system_libs.py#L846

It's not perfect - would be nice if the emsdk could set this up, that's a good idea.

**Comment by BenjaminTrapani** [comment]
Thanks, that worked perfectly!
