### ISSUE TITLE
Xcode.tar.gz not found

### ISSUE THREAD

**Issue by since2014** [emscripten-ports/SDL2#83]
The `Xcode.tar.gz` file mentioned in [docs/README-macosx.md](https://github.com/emscripten-ports/SDL2/blob/master/docs/README-macosx.md) is not found.

**Comment by Daft-Freak** [comment]
This repo is for the Emscripten port, looks like there's an [old report about this](https://bugzilla.libsdl.org/show_bug.cgi?id=1964) upstream though.
