### ISSUE TITLE
emscripten build unable to find linux/joystick.h

### ISSUE THREAD

**Issue by vmk1802** [emscripten-ports/SDL2#85]
system_libs:WARNING: retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_18.zip
system_libs:WARNING: unpacking port: sdl2
cache:INFO: generating port: libSDL2.bc... (this will be cached in "/home/lt/.emscripten_cache/asmjs/libSDL2.bc" for subsequent builds)
cache:INFO:  - ok
./joystick.c:4:9: fatal error: 'linux/joystick.h' file not found
#include<linux/joystick.h>
        ^~~~~~~~~~~~~~~~~~
1 error generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting

**Comment by Daft-Freak** [comment]
Is `joystick.c` in your code? It looks like the port built successfully and don't see a file called that anywhere in the repo. The only place I can see `#include <linux/joystick.h>` is in the linux joystick code which shouldn't be getting compiled...

**Comment by vmk1802** [comment]
It was my work space issue. This issue can be closed.
