### ISSUE TITLE
SDL_APP_TERMINATING on page exit

### ISSUE THREAD

**Issue by Beuc** [emscripten-ports/SDL2#88]
I'm considering how to save some of the game data when the player leaves the web page.

I believe that sending `SDL_APP_TERMINATING` on `window.beforeunload`, and offering the developer to catch it with a synchronous `SDL_AddEventWatch()` (the game won't have a change to run its event loop), would make the most sense in the SDL2 emscripten port.
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
https://wiki.libsdl.org/SDL_EventType
https://wiki.libsdl.org/SDL_AddEventWatch

I'm going to do some testing, let me know if that's something you'd appreciate a PR for :)

**Comment by Daft-Freak** [comment]
I think this came up while working on the initial port. There was an attempt at sending window close/quit events (https://github.com/gsathya/SDL-emscripten/commit/4c2637c909d481220ce4f3d5131bbe846132ef3e) which didn't work, but I wasn't aware of `SDL_AddEventWatch` back then.

**Comment by Beuc** [comment]
I pushed #89.
Please find attached a test app :)
[testbeforeunload.zip](https://github.com/emscripten-ports/SDL2/files/3510075/testbeforeunload.zip)
