### ISSUE TITLE
error: implicit declaration of function 'REPORT_RESULT' is invalid in C99

### ISSUE THREAD

**Issue by paldepind** [emscripten-ports/SDL2#9]
I've installed Emscripten as per [the instructions](http://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_linux.html#building-emscripten-on-linux).

However, when I try to compile any of [SDL2 tests](https://github.com/kripken/emscripten/tree/master/tests) I get the following error:

```
$ ./emcc tests/sdl2_mouse.c -s USE_SDL=2 -o out.js
tests/sdl2_mouse.c:30:11: error: implicit declaration of function 'REPORT_RESULT' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
          REPORT_RESULT();
          ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
```

The error seems to be related to [this resolved issue](https://github.com/kripken/emscripten/issues/2175).

**Comment by kripken** [comment]
The tests integrate into the test suite using that command, they aren't meant to be run standalone. But you can remove that line to make them work.

To run them from the test suite, you can do e.g. `tests/runner.py browser.test_sdl2_image`

**Comment by paldepind** [comment]
Ok. I simply assumed they where examples I could compile  and run. I probably got that impression since the tutorial told me to compile the `hello_world.c` file in the example directory as if it was an example program. Looking at some of the other files in the directory they appear to be example programs as well.

Maybe creating an examples directory specifically for the demonstration programs would be a good idea? Mixing tests an examples seems odd to me.

**Comment by kripken** [comment]
Yeah, I suppose it could be confusing. For now I explained this in the
tutorial. But maybe we should indeed create an examples/ folder.

- Alon
