### ISSUE TITLE
SDL_SetRelativeMouseMode causes Javascript exception

### ISSUE THREAD

**Issue by AbdelmalekIhdene** [emscripten-ports/SDL2#99]
I am trying to set up an FPS camera and to lock the mouse to the center of the screen. However, I am getting a Javascript exception upon trying to do so:
```
exception thrown: SyntaxError: '' is not a valid selector,__findEventTarget@http://localhost:8000/index.js:1:143800
_emscripten_request_pointerlock@http://localhost:8000/index.js:1:215484
@http://localhost:8000/index.js line 1 > WebAssembly.instantiate:wasm-function[1072]:0x6b7a9
@http://localhost:8000/index.js line 1 > WebAssembly.instantiate:wasm-function[500]:0xadd6
@http://localhost:8000/index.js line 1 > WebAssembly.instantiate:wasm-function[390]:0x520b
@http://localhost:8000/index.js line 1 > WebAssembly.instantiate:wasm-function[1377]:0x83ac3
Module.dynCall_vi@http://localhost:8000/index.js:1:287054
browserIterationFunc@http://localhost:8000/index.js:1:102793
runIter@http://localhost:8000/index.js:1:105962
Browser_mainLoop_runner@http://localhost:8000/index.js:1:104426
localhost:8000:1:516
```
Moreover, `SDL_CaptureMouse` does not do anything either.
It can be done since Doom has been ported successfully, but I personally do not know how to trap the camera properly.

**Comment by Daft-Freak** [comment]
Looks like this is the problem: https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenmouse.c#L241. Passing `NULL` for event targets used to be valid and use the default. But now with `DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR` (the default) it's an error. I think it needs to be something like `focused_window->driverdata->canvas_id`.

`-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0` should be a workaround for now.

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
@Daft-Freak 's comment is spot on here.

**Comment by Daft-Freak** [comment]
Fix probably looks like this: (untested)
```diff
diff --git a/src/video/emscripten/SDL_emscriptenmouse.c b/src/video/emscripten/SDL_emscriptenmouse.c
index c7f2221c0..2597a7c7f 100644
--- a/src/video/emscripten/SDL_emscriptenmouse.c
+++ b/src/video/emscripten/SDL_emscriptenmouse.c
@@ -28,6 +28,7 @@
 #include <emscripten/html5.h>
 
 #include "SDL_emscriptenmouse.h"
+#include "SDL_emscriptenvideo.h"
 
 #include "../../events/SDL_mouse_c.h"
 #include "SDL_assert.h"
@@ -236,9 +237,19 @@ Emscripten_WarpMouse(SDL_Window* window, int x, int y)
 static int
 Emscripten_SetRelativeMouseMode(SDL_bool enabled)
 {
+    SDL_Window *window;
+    SDL_WindowData *window_data;
+
     /* TODO: pointer lock isn't actually enabled yet */
     if(enabled) {
-        if(emscripten_request_pointerlock(NULL, 1) >= EMSCRIPTEN_RESULT_SUCCESS) {
+        window = SDL_GetMouseFocus();
+        if (window == NULL) {
+            return -1;
+        }
+
+        window_data = (SDL_WindowData *) window->driverdata;
+
+        if(emscripten_request_pointerlock(window_data->canvas_id, 1) >= EMSCRIPTEN_RESULT_SUCCESS) {
             return 0;
         }
     } else {

```

(Need to get the right machine to behave so that I can build...)

**Comment by Daft-Freak** [comment]
Almost, there was another call... Branch with fix (lightly tested): https://github.com/emscripten-ports/SDL2/tree/pointer_lock_id

**Comment by danielknobe** [comment]
I came across the issue in my project.
emscripten_request_pointerlock should not be called with NULL.
I have build SDL2 from branch
https://github.com/emscripten-ports/SDL2/tree/pointer_lock_id
and linked it to my project.

I did some tests and it the fix seems to work great!
I think the patch should be merged to master.
